"""Dom Casmurro — decisões editoriais.

EMENDAS: intervenções no texto-base, na grafia da 1ª edição: (tipo, trecho, troca)
  'erro'    erro tipográfico evidente da 1ª edição (corrigido como na tradição posterior)
  'edicao'  lição comum a toda a tradição posterior (provável 2ª edição, 1900)
  'ocr'     erro das transcrições digitais; a 1ª edição traz a forma correta (conferido no fac-símile)
AJUSTES: depois da modernização, em tokens separados por espaço: (tipo, antes, de, para, depois)
MANUAL: grafia moderna de palavras que as edições de referência não resolvem
VERSOS: parágrafos que a 1ª edição compõe como versos
TITULOS: títulos corrigidos pelo índice
"""

EMENDAS = [
    ('erro', "toda a cara, todo a pessoa", "toda a cara, toda a pessoa"),
    ('erro', "no sentido do dividirmos", "no sentido de dividirmos"),
    ('erro', "Virtudes eternas. Em amava", "Virtudes eternas. Eu amava"),
    ('erro', "pé do sabugueiro", "pé de sabugueiro"),
    ('erro', "escrevo todos os noites que é em desespero", "escrevo todas as noites que é um desespero"),
    ('erro', "cresce na madurera", "cresce na madureza"),
    ('erro', "falava della muitos vezes", "falava della muitas vezes"),
    ('erro', "passasse. Quanto tornei", "passasse. Quando tornei"),
    ('erro', "campainha nos mãos", "campainha nas mãos"),
    ('erro', "sua homoepathia", "sua homeopathia"),
    ('erro', "puzestes aos mãos", "puzestes as mãos"),
    ('erro', "por baixo do cabeça", "por baixo da cabeça"),
    ('erro', "Ficámos naquelle luta", "Ficámos naquella luta"),
    ('erro', "batia mais mais nem menos", "batia mais nem menos"),
    ('erro', "Que não será? « A nossa", "Que não será? » A nossa"),
    ('erro', "bateu-me na casa", "bateu-me na cara"),
    ('erro', "como fez os mãos limpas", "como fez as mãos limpas"),
    ('erro', "ajudal-os, faziam o seu", "ajudal-os, fazia o seu"),
    ('erro', "aqui eu latim", "aqui em latim"),
    ('erro', "adivinhei que trazia as meias", "adivinhei que traziam as meias"),
    ('erro', "relancei do olhos", "relancei os olhos"),
    ('erro', "na quintal della", "no quintal della"),
    ('erro', "de os infringir", "de as infringir"),
    ('erro', "Capitú fel-o mais", "Capitú fel-a mais"),
    ('erro', "Da cama ouvia voz", "Da cama ouvi a voz"),
    ('erro', "Repeti esta palavras", "Repeti estas palavras"),
    ('erro', "A muitas outros", "A muitos outros"),
    ('erro', "onde o perfeição", "onde a perfeição"),
    ('erro', "tarde do março", "tarde de março"),
    ('erro', "Pois nem todo isso", "Pois nem tudo isso"),
    ('erro', "ser Desmosthenes", "ser Demosthenes"),
    ('erro', "nelle todos as vocações", "nelle todas as vocações"),
    ('erro', "os gestos, as modos", "os gestos, os modos"),
    ('erro', "resposta do Capitú", "resposta de Capitú"),
    ('erro', "saber de modelo", "saber do modelo"),
    ('erro', "Expliquei-lhe que tenha saido", "Expliquei-lhe que tinha saido"),
    ('erro', "naquelle noite da Gloria", "naquella noite da Gloria"),
    ('erro', "porque e não nos visita", "porque é que não nos visita"),
    ('erro', "tem andando mais", "tem andado mais"),
    ('erro', "Muitos homem choravam", "Muitos homens choravam"),
    ('erro', "oito hora n'uma", "oito horas n'uma"),
    ('erro', "filha. Todo isso", "filha. Tudo isso"),
    ('erro', "numero dos paginas", "numero das paginas"),
    ('erro', "todas os minutos", "todos os minutos"),
    ('erro', "não foi o bordo", "não foi a bordo"),
    ('erro', "Quem lhe importará", "Quem se importará"),
    ('erro', "esperar um dez", "esperar uns dez"),
    ('erro', "fundo, disfarçamente tragico", "fundo, disfarçadamente tragico"),
    ('erro', "sorriso que a accendou", "sorriso que a accendeu"),
    ('erro', "antes do conclusão", "antes da conclusão"),
    ('erro', "toma o benção", "toma a benção"),
    ('edicao', "É o que vás entender", "É o que vaes entender"),
    ('edicao', "ao ler o que vás ler", "ao ler o que vaes ler"),
    ('edicao', "vários outros. Vás agora", "vários outros. Vaes agora"),
    ('edicao', "Já me vás entendendo", "Já me vaes entendendo"),
    ('edicao', "pessoa de familia", "pessoa da familia"),
    ('edicao', "primeira tarde, em que", "primeira parte, em que"),
    ('edicao', "a buscava do lado opposto", "a buscava do outro opposto"),
    ('edicao', "que Deus me dera", "que Deus lhe dera"),
    ('edicao', "me não deitar depois de jantar", "me não deitar depois do jantar"),
    ('edicao', "espantado. ¶ — Ouvi o que", "espantado. ¶ — Ouviu o que"),
    ('edicao', "a mór parte", "a maior parte"),
    ('ocr', "boas pessoas, excedentes", "boas pessoas, excellentes"),
    ('ocr', "mais intima palavra", "mais infima palavra"),
    ('ocr', "transferisse a altitude", "transferisse a attitude"),
    ('ocr', "pouco appareco", "pouco appareço"),
    ('ocr', "faziam giros, avançando ou", "faziam giros, avoaçando ou"),
    ('ocr', "atalhou promplamente", "atalhou promptamente"),
    ('ocr', "respondendo promplamente", "respondendo promptamente"),
    ('ocr', "moço muito distineto", "moço muito distincto"),
]

AJUSTES = [
    # pontuação atestada por toda a tradição posterior (provável 2ª edição)
    ('pontuacao', "Sucedeu , porém , que", "", ",", "como eu estava cansado"),
    ('pontuacao', "( e enchia-o novamente )", "", ",", "este cálix é"),
    ('pontuacao', "« É surda , coitada ! »", "", ",", "exclamava Capitu"),
    ('pontuacao', "do mal que nos esperava", ",", ";", "mas o pai era"),
    ('pontuacao', "sobre os textos roídos", ",", "", "fosse ainda um modo"),
    ('pontuacao', "Capitu , a princípio", "", ",", "não disse nada"),
    ('pontuacao', "porque ele é tão religioso", ",", "", "como este lampião"),
    ('pontuacao', "falou como você não imagina", ".", "...", "¶ — Mas falou"),
    ('pontuacao', "« Prima Justina , você que acha ? »", "", ",", "a minha resposta era"),
    ('pontuacao', "o cabelo todo , isso", ",", "", "sim"),
    ('pontuacao', "Isto ? redarguiu Capitu", "", ",", "desfazendo as tranças"),
    ('pontuacao', "obedeceria ao primeiro versículo", ";", ":", "« Aplique"),
    ('pontuacao', "parado . Foi ela", "", ",", "entretanto , que me tirou"),
    ('pontuacao', "de mão-cheia . Também", "", ",", "se não vier"),
    ('pontuacao', "um sermão do padre X ...", "", ",", "uma vigairaria mineira"),
    ('pontuacao', "Não escolhi logo , logo", "", ",", "o soneto"),
    ('pontuacao', "em latim", ") porquanto ,", ") , porquanto", "a senhora tinha"),
    ('pontuacao', "vinda a casa . Minha mãe", "", ",", "depois que lhe respondi"),
    ('pontuacao', "assim como dão com força", "", ",", "assim também se vão"),
    ('pontuacao', "com Sinhazinha Gurgel", ".", ":", "¶ — Por que não vais"),
    ('pontuacao', "dizendo ao ver-nos abraçados", ".", ":", "¶ — Mulher"),
    ('pontuacao', "perguntou José Dias", "", ",", "endireitando o tronco"),
    ('pontuacao', "como soube depois )", ",", "", "e perguntava-lhe"),
    ('pontuacao', "com mares maiores , muito maiores .", "—", "", "Você não imagina"),
    ('pontuacao', "a ressaca era grande", ",", "", "e , a distância"),
    ('pontuacao', "a virtude , filha dela", "", ",", "é , genealogicamente"),
    ('pontuacao', "do homem que recebera", "defunto", ", defunto ,", "aqueles olhos"),
    ('pontuacao', "que os compiladores", ",", "", "podem tirar daqui"),
    ('pontuacao', "¶ — Mas", ",", "", "passa ; o que"),
    ('pontuacao', "ao mirar o filho dormindo", "", ",", "pensara na filhinha"),
    ('pontuacao', "Até a voz", ";", ",", "dentro de pouco"),
    ('pontuacao', "se a conhecessem", ",", "", "mandariam esculpir"),
    ('pontuacao', "explicações que dei ao arquiteto", "", ",", "segundo contei em tempo"),
    ('pontuacao', "menos cheio de corpo", ",", "", "e , salvo as cores"),
    ('pontuacao', "e maiores recomendações", ":", ".", "¶ — Levas"),
    # «que» átono nas locuções («assim que», «pelo que», «sem o que»): sem acento
    ('grafia', "de menear . Assim", "quê", "que", ", eu não era"),
    ('grafia', "aos apóstolos . Assim", "quê", "que", ", ele e eu"),
    ('grafia', "duvidar dela . Assim", "quê", "que", ", sem atender"),
    ('grafia', "da minha amiga ; pelo", "quê", "que", ", não admira"),
    ('grafia', "no tempo , sem o", "quê", "que", "tudo é calado"),
    # lição das três primeiras edições («É bem»), contra a vulgata («E bem»)
    ('leitura', "casca . ¶", "E", "É", "bem , qualquer que seja"),
]

MANUAL = {
    "cincoenta": "cinquenta", "creanca": "criança", "creancas": "crianças", "funccões": "funções",
    "desapparecam": "desapareçam", "Job": "Jó", "forca": "força", "moco": "moço", "trancas": "tranças",
    "sabbabos": "sábados", "rans": "rãs", "almanaks": "almanaques", "tres": "três", "applaudiu": "aplaudiu",
    "lh'o": "lho", "tilbury": "tílburi", "promptamente": "prontamente", "distincto": "distinto",
}

VERSOS = {
    'Oh! flor do céu! oh! flor cândida e pura!': ['Oh! flor do céu! oh! flor cândida e pura!'],
    'Perde-se a vida, ganha-se a batalha!': ['Perde-se a vida, ganha-se a batalha!'],
    'Ganha-se a vida, perde-se a batalha!': ['Ganha-se a vida, perde-se a batalha!'],
    'Ela amou o que me afligira, Eu amei a piedade dela.': ['Ela amou o que me afligira,', 'Eu amei a piedade dela.'],
    'Rinovellate di novelle fronde.': ['Rinovellate di novelle fronde.'],
    'BENTO CAPITOLINA': ['BENTO', 'CAPITOLINA'],
}

TITULOS = {'CXLVIII': 'É bem, e o resto?'}   # índice das três primeiras edições
