/* Poesia de Charles Baudelaire: texto dos poemas e notas sobre o texto.
   Gerado por ferramentas/poesia.py; não edite à mão.

   Texto: um verso por linha; estrofes separadas por linha em branco; linhas com "::" são marcas
   (::parte, ::subtitulo, ::fala, ::voz, ::epigrafe, ::dedicatoria, ::data, ::fecho, ::separador,
   ::lacuna, ::pagina). Nas traduções, "o" traz o original, parte por parte.
*/
BIBLIOTECA.textos({
"o-albatroz": {"t":["Muitas vezes, por jogo, os homens da equipagem\nApanham o albatroz, ave imensa do largo,\nQue segue, sem afã, parceiro de viagem,\nO barco, a deslizar sobre um abismo amargo.\n\nMal o depõem, enfim, nas tábuas do convés,\nO grande rei do azul, canhestro e envergonhado,\nDeixa, que dó!, cair as asas a seus pés,\nComo remos no solo, a arrastar-se de lado.\n\nO alado viajor, como é tosco e indefeso!\nFeio e grotesco, agora, o que antes encantava!\nUm lhe mete no bico o seu cachimbo aceso,\nOutro, mancando, imita aquele que voava!\n\nO Poeta é igual ao príncipe dos ares\nQue frequenta a tormenta, a rir do arqueiro, no ar;\nExilado no chão, entre vaias e esgares,\nAs asas de gigante impedem-no de andar."],"e":{"titulo":"Sobre esta tradução","apresentacao":"**Original.** _L’Albatros_, de Charles Baudelaire: Les Fleurs du mal, 2.ª ed. (Paris, Poulet-Malassis et de Broise, 1861), II.\n\n**Metro do original.** Alexandrino clássico francês: 6 + 6 sílabas, cesura fixa; rimas cruzadas, alternando femininas e masculinas.\n\n**Metro da tradução.** Alexandrino clássico português, com a lei do hemistíquio: 6.ª sílaba tônica e fim de palavra na cesura; rimas cruzadas ABAB.\n\nO alexandrino tem equivalente direto: o de Bilac e Raimundo Correia, que respeita a cesura como o francês. Cada verso tem tônica na 6.ª e na 12.ª, e os demais tempos variam, como em Baudelaire.","fontes":[{"nome":"Texto original: Wikisource","url":"https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)/L’Albatros"}]},"o":["Souvent, pour s’amuser, les hommes d’équipage\nPrennent des albatros, vastes oiseaux des mers,\nQui suivent, indolents compagnons de voyage,\nLe navire glissant sur les gouffres amers.\n\nÀ peine les ont-ils déposés sur les planches,\nQue ces rois de l’azur, maladroits et honteux,\nLaissent piteusement leurs grandes ailes blanches\nComme des avirons traîner à côté d’eux.\n\nCe voyageur ailé, comme il est gauche et veule !\nLui, naguère si beau, qu’il est comique et laid !\nL’un agace son bec avec un brûle-gueule,\nL’autre mime, en boitant, l’infirme qui volait !\n\nLe Poëte est semblable au prince des nuées\nQui hante la tempête et se rit de l’archer ;\nExilé sur le sol au milieu des huées,\nSes ailes de géant l’empêchent de marcher."]}
});
